### PR TITLE
Reducer action

### PR DESCRIPTION
**Pull request by Salwa99**
# Use Redux in React components
### Heyo :wave: 

**In this PR I:**

1. Refactor the code to make sure  that the state immutable in reducers.
2. Pass an array of books as an initial state for the books reducer
3. Import Redux Provider and the store in the main component then connect the app to the Redux store. 
4. Display books
5.  Use Redux useDispatch to Add, Remove books and Check status
6. Fix linters errors
7. Follow GitFlow

_Cheers_

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Salwa99, kindly add the key features section to your readme

**Comment by Salwa99** [comment]
@prolajumokeoni  what should I add exactly

**Comment by prolajumokeoni** [comment]
Hi @Salwa99, you are missing the key features section in your readme, please add it

**Review by prolajumokeoni — APPROVED** [review]
Hi @Salwa99 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀  
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Salwa99** [comment]
@prolajumokeoni   you for mentioning the issue in the Readme file😊

**Pull request merged**
